<link href="<?php echo PATH?>src/assets/images/favicon.ico" rel="shortcut icon">
<link href="<?php echo PATH?>src/css/estilos.css" rel="stylesheet" >
<link href="<?php echo PATH?>src/assets/libs/sweetalert2/sweetalert2.min.css" rel="stylesheet" type="text/css">
<link href="<?php echo PATH?>src/assets/css/app.min.css" rel="stylesheet" type="text/css">
<link href="<?php echo PATH?>src/assets/css/icons.min.css" rel="stylesheet" type="text/css">
<link href="<?php echo PATH?>src/assets/libs/gridjs/theme/mermaid.min.css" rel="stylesheet" type="text/css">
<script src="<?php echo PATH?>src/assets/js/pages/table-gridjs.js" defer ></script>
<script src="<?php echo PATH?>src/assets/libs/gridjs/gridjs.umd.js" defer ></script>
<script src="<?php echo PATH?>src/assets/js/config.js" defer ></script>
<script src="<?php echo PATH?>src/assets/libs/prismjs/prism.js" defer ></script>
<script src="<?php echo PATH?>src/assets/libs/prismjs/plugins/normalize-whitespace/prism-normalize-whitespace.min.js" defer ></script>
<script src="<?php echo PATH?>src/assets/libs/clipboard/clipboard.min.js" defer ></script>
<script src="<?php echo PATH?>src/assets/libs/simplebar/simplebar.min.js" defer ></script>
<script src="<?php echo PATH?>src/assets/libs/feather-icons/feather.min.js" defer ></script>
<script src="<?php echo PATH?>src/assets/libs/@frostui/tailwindcss/frostui.js" defer ></script>
<script src="<?php echo PATH?>src/assets/js/app.js" defer ></script>
<script src="<?php echo PATH?>src/assets/libs/sweetalert2/sweetalert2.min.js" defer ></script>
<script src="<?php echo PATH?>src/assets/js/pages/extended-sweetalert.js" defer ></script>
<script src="<?php echo PATH?>src/assets/js/pages/highlight.js" defer ></script>
<script src="<?php echo PATH?>src/assets/libs/apexcharts/apexcharts.min.js" defer ></script>
<script src="<?php echo PATH?>src/assets/js/pages/charts-apex.js" defer ></script>
